# Generated by Django 3.2.3 on 2021-05-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '未知')], default=0, verbose_name='性别')),
                ('profession', models.CharField(max_length=255, verbose_name='职业')),
                ('email', models.EmailField(max_length=255, verbose_name='邮箱')),
                ('qq', models.CharField(max_length=255, verbose_name='QQ')),
                ('phone', models.CharField(max_length=255, verbose_name='电话')),
                ('status', models.IntegerField(choices=[(1, '申请'), (2, '通过'), (0, '拒绝')], default=0, verbose_name='审核状态')),
                ('create_t', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_t', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
    ]
